### PR TITLE
fix minimumNonceByAccount

### PR DESCRIPTION
**Pull request by xyunsh**
not minimum nonce by account, but the last nonce by account

### CODE REVIEW

**Comment by epheph** [comment]
Thank you for the PR. It's not immediately obvious to me, does this generate a different object?

**Comment by xyunsh** [comment]
> Thank you for the PR. It's not immediately obvious to me, does this generate a different object?

I think the purpose of the minimumNonceByAccount function is to get the minimum nonce for each account, but the original function gets the last nonce for each account, which causes calling the wait function to throw an "account nonce too high" exception.

**Comment by asir6** [comment]
Any chance to include this fix in the build?  Getting "nonce too high" error 2 out of 5 in my send bundle requests.

**Comment by epheph** [comment]
I see the issue finally. thanks.

@asir6 are you sure this specific issue is causing your nonce-too-high error? It could happen for a number of reasons. i'll get this deployed.

**Comment by epheph** [comment]
Fixed in v0.4.2

**Comment by asir6** [comment]
> I see the issue finally. thanks.
> 
> @asir6 are you sure this specific issue is causing your nonce-too-high error? It could happen for a number of reasons. i'll get this deployed.

thanks @epheph , I am not sure if the nonce-too-high error was caused by this.  I upgraded to 0.42 and the error occurs less than before, but still exists.   
I just keep sending the same tx until it succeeds on every block, some of the blocks give nonce-too-high errors.  
I also tried to resolve this by giving tx a proper nonce (by `provider.getTransactionCount(address, 'pending')`), however, some of the blocks give nonce-too-low error this time.

**Pull request merged**
