### PR TITLE
Include bundleHash in sendBundle Response

### PR DESCRIPTION
**Pull request by ethermachine**
Include bundleHash in sendBundle Response

### CODE REVIEW

**Comment by epheph** [comment]
Good idea. Can you add the new attribute to the type?

https://github.com/flashbots/ethers-provider-flashbots-bundle/blob/42e66aace6b13a6579f9fe936216240f11cc391b/src/index.ts#L38-L42

Thanks!

Separately, we should have a function that can calculate the bundleHash, without requiring interaction with the server. But saving the one that comes back is useful.

Thanks!

**Comment by ethermachine** [comment]
@epheph Done!

**Review by epheph — APPROVED** [review]
Looks good!

**Comment by ethermachine** [comment]
> Separately, we should have a function that can calculate the bundleHash, without requiring interaction with the server. But saving the one that comes back is useful.

This would be awesome (especially for me!) but I don't have enough knowledge to make it in client side, and code behind RPC is not open-sourced, right?

Look forward to see that feature implemented!

**Pull request merged**
